### PR TITLE
Update Python releases support

### PR DESCRIPTION
**Pull request by mfld-fr**
Issue #104:
- Added 3.7, removed 3.3 and 3.4 (3.7 on hold until Travis supports it)
- Removed unused third-party Zip packages from Travis configuration
- Updated README

### CODE REVIEW

**Comment by mfld-fr** [comment]
Looks like Travis is not supporting Python 3.7 yet...

**Comment by macfreek** [comment]
Good cleanup.

That zip code was there because prior to Python 2.7.9, it was simply not possible to download https://github.com/downloads/twoolie/NBT/Sample_World.tar.gz, which is done as part of the Travis test.

(Background: at the time, some mayor flaws were found in SSL, and github dropped support for SSLv3, and Python 2.7.8 was only capable of doing TLSv1.0 by first connecting with SSLv3 and then negotiating a better security level. Basically, the Python 2 ssl module was broken behind repair. In the end, this was fixed by a ["unprecedented in a "bugfix" release" of Python](https://www.python.org/downloads/release/python-279/), which was of course not a bugfix release, but a feature release, but the Python team once told no 2.8 would ever be released, so they just _named_ it a bugfix release. Glad that got fixed. In retrospect, we did too much work to maintain backwards compatibility. So, I'm happy that all this work-around code is gone now.)

**Comment by mfld-fr** [comment]
What is pleasant while contributing to this project is that I learn many tips & tricks around Python :smile:. Thanks for the merge !

**Comment by macfreek** [comment]
A bit off-topic, but what I learned from this project is documentation, as well as unit tests. Travis is great to make sure things don't break accidentally. It still can be improved. That's what the coveralls.io button is for: it checks how much of the code was executed during a check. We need more tests :)

Looking back at the code (which I didn't touch in some years) is that some of the comments are useful, and that we need less workarounds.

**Pull request merged**
