### PR TITLE
Add PyCharm .idea folder to .gitgnore

### PR DESCRIPTION
**Pull request by Borkason**

### CODE REVIEW

**Comment by macfreek** [comment]
Hi Borkason,

I understand your changes, but as it is, I would not favour committing these to the master branch:
* `.idea` indeed belong to a `.gitignore` file, but as I understand, it is common to only add project-specific files in the project's `.gitignore` file. User-specific files that you like to ignore should go in a user-specific `.gitignore` file. See https://stackoverflow.com/questions/5724455/ how to create one.
* Python is case-sensitive, so changing `TAG_*` to `Tag_*` makes the library backwards incompatible, resulting in a burden to existing users of the library.

**Comment by macfreek** [comment]
@Borkason I am looking forward to other improvements you have for NBT! (I noticed your request #99 and you are right about that broken URL).

**Comment by Borkason** [comment]
@macfreek I'm playing around with it. I actually only wanted to push the gitignore change. I have no idea how the other one slipped in there, especially because I did that change a lot later, when I was playing with the code in my own repository.

**Comment by macfreek** [comment]
> @macfreek I'm playing around with it. I actually only wanted to push the gitignore change. I have no idea how the other one slipped in there, especially because I did that change a lot later, when I was playing with the code in my own repository.

I expect on of the quirks of Github played up: if you make a pull request from your master branch to twoolie's master branch, and you later make another commit to your master branch, this new commit will be added to the pull request as well. The solution is to create a temporary branch that only contains the intended commits.

**Pull request closed without merging**
