### PR TITLE
Add really simple example for scoreboards.

### PR DESCRIPTION
**Pull request by fwaggle**
Hi,

I dunno how useful this will be, I basically took one of the other examples and hacked it up to parse data/scoreboard.dat and dump out scores for all the objectives.

In my own stuff I ended up dumping this out in JSON format, but the code is rather yucky so I tried to keep things simple here (none of the other examples appear to dump JSON output).

Just thought I'd say thanks for the tool by sharing what I had.

### CODE REVIEW

**Comment by macfreek** [comment]
Sorry for ignoring this for so long. This may be useful to users. Could you also provide a sample `scoreboard.dat` file?

**Comment by fwaggle** [comment]
Hi, No problem ignoring it, the code was in the repo last time I want it so that's all I really mind about. :)

What do you mean provide a sample scoreboard file? I don't see anywhere in the tree where a sample world file is included, and the scoreboard.dat is just part of any world directory. I can probably send you one if all you want to do is play with it though.

**Comment by macfreek** [comment]
We like to create a unit test for each example script, feed it a known file, and check the output. I need a test file for that. I only found two scoreboard.dat files in my local computer, and they only contain one player, myself. For a better test, I like a more realistic example.

**Comment by fwaggle** [comment]
Ahh righto, I'll see what I can do.

**Comment by fwaggle** [comment]
Hey guys,

I haven't had a lot of time to spare recently, but I noticed this hanging.

After grabbing the scoreboard from an old Minecraft server my wife ran: https://www.dropbox.com/s/07y6ag2bzg81whc/scoreboard.dat?dl=0

I smashed out a really awful test script for it that more or less confirms it works that I'll commit in just a second. I don't think it's a particularly good set of tests, but it's a point in the right direction. I'm completely okay if you just want to take what I've done and rewrite it yourselves, I relinquish all copyright, use it under whatever license you like, I don't care. I just found your tool handy and just wanted to say thanks by contributing what I'd worked out.

If you want to come up with a better scoreboard file, I blogged about how I set the scoreboard up:

http://www.fwaggle.org/2015/03/minecraft-scoreboards.html

and you can see documentation for the other objectives here:

http://minecraft.gamepedia.com/Scoreboard#Objectives

I didn't commit the scoreboard.dat file, because even though it's only 400 bytes or so, I'm not sure if git is the correct place for it?

If you want me to try clean this up a little more, squish it, and get it ready so you can just commit it as is, I'll try and get it done at some point in the future, maybe a little more timely than this last update. :)

**Comment by twoolie** [comment]
@fwaggle any chance you can commit that 400 byte scoreboard file with the rest of the test files?

**Comment by fwaggle** [comment]
@twoolie Sorry it's been so long, I was overseas and then been busy with other stuff since I got back. I'll see what I can do this weekend about organizing some proper tests, and seeing why the CI build failed.

**Comment by mfld-fr** [comment]
@fwaggle's work recovered in #107. You could close this one now.

**Comment by fwaggle** [comment]
Closing, I have no time to make the test cases decent and I definitely don't have time to play Minecraft lately. :(

**Comment by mfld-fr** [comment]
Hey @fwaggle, looks like there is a misunderstanding there. You actually don't need to find any time for that, because I already picked your work, reworked the unit test and submitted the whole as a new PR (#107 : "Scoreboard example 'reloaded'"). So even if you close this old one, your contribution is not lost and will be merged in the new one. You have nothing more to do. Don't worry, be happy :smile: !

**Comment by fwaggle** [comment]
@mfld-fr thanks so much! I've been meaning to do something about this for a long time, really appreciate you taking the time to make something out of it!

**Pull request closed without merging**
