### PR TITLE
More support of "flattened" Anvil format

### PR DESCRIPTION
**Pull request by mfld-fr**
- Add new class AnvilChunk & AnvilSection as requested in TODO
- Start to replace block numeric identifiers by alpha ones at user level
- Extend class McRegionChunk
- Update `anvil_blockdata` example
- Update `map` example

### CODE REVIEW

**Comment by macfreek** [comment]
Seems good, thanks you for working on it and creating a patch!

Only comment I would have is to raise a different exception if a section is not defined. I would raise a different LookupError (perhaps a `class InconceivedSection(LookupError)`), so that the chunk code does not have to reply on the region code. The reason is that I want to avoid a potential circular dependency where `region` depends on `chunk` and `chunk` depends on `region`.

Is it OK if I accept the pull with this change?

**Comment by mfld-fr** [comment]
Well, actually, I am not satisfied by this first change and I made more changes that I will push after more testing, so I put a `WIP:` in the MR title to hold it and to get that upcoming changes reviewed.

Not only I have to fix the circular dependency as you said, but I also have to work on the right way to handle block identifiers in a generic manner: current MC version uses alpha identifiers, while old versions used numeric ones. So I am trying to make a comprehensive API with alpha identifiers, and to hide the old numeric ones in case we are reading an old version, with a switch on the "DataVersion" tag.

Stay tuned !

**Comment by mfld-fr** [comment]
As expected, the Travis build failed because the test world is still an old version, and I have not yet put back the decoding of the legacy block data. Scheduled for a next commit.

**Comment by macfreek** [comment]
I'm happy to accept anything that passes all tests, including a change to remove outdated tests ;)
The chunk code is very old, and I've seen few (if any) issues on it last years, so I suspect that most people use the examples. Any change should not break other code such as [Minecraft-Region-Fixer](https://github.com/Fenixin/Minecraft-Region-Fixer/), but I'm fairly sure it does not use the chunk part.

But I'm very happy to see this code, as it may make the library more useful, so just let me know when you think it is ready, and I try to merge after a review.

**Comment by macfreek** [comment]
A bit of clarification: this library is maintained for over 8 years now, and the core parts: `nbt.nbt` and `nbt.region` are fairly solid. I would write it differently if I were to write it today, but the code is fairly mature. `nbt.world` and `nbt.chunk` are nice, but have not matured that much. Some of it's functionality was gradually moved to examples, to note to users that that part was provided 'as is'.

I would be thrilled to see more functionality in the core, especially logic when it comes to undefined sections, as well as some helper functions for all the extra files (like scoreboard.dat). However, if you want to add a lot of very Minecraft-specific code, be sure to discuss it, to avoid adding maintenance code.

It's a pity the NBT format gained no traction outside the Minecraft world. I think it's fairly elegant. However, other 'dynamic binary data' file format have prevailed. The one am actively using at work is [Google protobuf](https://github.com/protocolbuffers/protobuf/).

**Comment by mfld-fr** [comment]
The latest commit fixes the regression on the `map` unit test. Well... looks like we can now consider this latest version as a merge candidate.

nbtmcregionovr4kt8u

**Comment by mfld-fr** [comment]
The Travis build job 93.7 failed not because of the map unit test, but after the 10 mins timeout. See https://travis-ci.org/twoolie/NBT/jobs/493402436.

**Comment by mfld-fr** [comment]
Again the same world, but after commenting out the `block_ignore` array:

world_region 1

Hey, this project begins to be a real cheat tool :smirk: !

**Comment by macfreek** [comment]
At first glance, this seems great. Of course, I was sold at seeing these pictures 👍

I particularly like how to seem to have simplified the math code in `examples/anvil_blockdata.py`.

There are two minor issues I see at first glance:
* AnvilSection is defined as `class AnvilSection:`. This is prefectly fine for Python 3, but for Python 2.7 this might be `class AnvilSection(object):`. Frankly, I no longer use Python 2.7, and see no problems in bumping the minimum version to 3.4. However, let's see what Travis has to say.
* some changes in commit ac1249a seem cosmetic. For example, `def __init__(self, nbt):` is changed to `def __init__ (self, nbt):`. However, the PEP8 recommendation is not to have spaces after a opening or closing bracket (you can check with a tool like `flake8`). Is there a reason to introduce a PEP8 deviation here?

**Comment by macfreek** [comment]
Errrm, I need sleep. Travis did pass. I guess the `(object)` frase now really is redundant. Good, I learned something! With the small PEP8 changes, I would vote to merge this.

**Comment by mfld-fr** [comment]
According to Python documentation, `object` inheritance is required in 2.x only when using some modern class features (see https://docs.python.org/2.7/reference/datamodel.html#newstyle). As we should follow the life cycle of the official Python versions (today 2.7, 3.5, 3.6 and 3.7), we should keep in mind that point, even if the Travis build passed. So thanks for the tip, I was not aware of that.

**Comment by mfld-fr** [comment]
There is no "good" reason to diverge from PEP8, above personal habits, so I will push a corrective commit on the spacing. Sorry for the waste.

**Comment by mfld-fr** [comment]
Fixed the spacing and object inheritance in the latest commit.

**Comment by mfld-fr** [comment]
Again a Travis failure in only one job (95.5), while copying a file, without any link with the latest commit...

**Comment by macfreek** [comment]
@mfld-fr please report if you think your commits are good enough to push to master, and I'm happy to merge. I'm less responsive next four days. Feel free to ping using a '@macfreek' comment, and I'll pick it up within a few days.

**Comment by mfld-fr** [comment]
@macfreek : yes, I think the proposed code is now in a good state after the last commit related to performance, and that you could merge.

**Comment by mfld-fr** [comment]
@macfreek Gentle reminder

**Comment by mfld-fr** [comment]
@twoolie @macfreek @MostAwesomeDude @MidnightLightning Hello, anyone to press the green button, please ? I am waiting for this merge to rebase and push more things...

**Comment by mfld-fr** [comment]
Thanks for the merge !

**Pull request merged**
