### PR TITLE
Add mfld-fr as contributor.

### PR DESCRIPTION
**Pull request by macfreek**
Thank you, @mfld-fr!

### CODE REVIEW

**Comment by macfreek** [comment]
@mfld-fr could you review how you like to be credited? (as mfld-fr, MFLD, your name or nickname, ...)

**Comment by mfld-fr** [comment]
Oooh... that's so cute... thank you so much, but really, that's too much for a few lines of code. I did it because that library came handy when I needed it, and pushing my updates is just... how to say ?.. the "normal user behavior" in the FOSS world. Please forget your idea, pulling my PR's is enough to recognize my contribution as it is automatically recorded by GitHub :smile:.

**Comment by twoolie** [comment]
It's a small library, a few lines of code make a big difference. Thankyou for your contributions, please let us add you to the contributors list :-)

**Comment by macfreek** [comment]
Beside well-deserved credit, an authors/contributors log also serves an important value in FOSS: it establishes ownership, which is important due to licensing.

For example, at some point in time, OpenSSL had to contact every contributor for legal reasons, and it was important to have an established list of authors. If you every write code that even remotely may be considered for inclusion in the Linux kernel, you have to "sign off" that you not only contributed by actually wrote that code, and hold the copyright. For NBT, we think that's a bit overkill, but establishing a list of authors is important.

(If you care to know why OpenSSL had to contact all authors: it was incompatible with GPL, and it was easier to either [completely rewrite it from scratch](https://en.wikipedia.org/wiki/GnuTLS) or [contact all previous contributors](https://license.openssl.org/). Trust me, choosing the right licensing is important. I wrote some [recommendation on software licenses](http://www.macfreek.nl/memory/Software_Licenses) in case you care.)

**Comment by mfld-fr** [comment]
OK, I understand the rational around licensing concern. Please add me as "mfld.fr", because it is my personal internet domain name used to aggregate things. Thanks for your explanations !

**Pull request merged**
